version: "3.7"

services:
  
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_DATABASE: timlog
#      MYSQL_ROOT_PASSWORD: 123
    networks:
      - timdbdef
    ports:
      - "13306:3306"    

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
    links:
      - db
    depends_on:
      - db
    networks:
      - timdbdef
    ports:
      - "18080:8080"

  tim-dbdef:
    build: ./
    depends_on:
      - db
    tty: false
    env_file: env_tim_dbdef
    networks: 
    - timdbdef


  portainer-ce:
#   image: portainer/portainer-ce
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
    - 9000:9000
    - 8000:8000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data

volumes:
  portainer_data:   

networks:
  timdbdef:
  